/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    'catalog': RouteRecordInfo<'catalog', '/menu', Record<never, never>, Record<never, never>>,
    'create-order': RouteRecordInfo<'create-order', '/menu/create-order', Record<never, never>, Record<never, never>>,
    'created-order': RouteRecordInfo<'created-order', '/menu/create-order/:orderId', { orderId: ParamValue<true> }, { orderId: ParamValue<false> }>,
    'orders': RouteRecordInfo<'orders', '/orders', Record<never, never>, Record<never, never>>,
    'orderId': RouteRecordInfo<'orderId', '/orders/:orderId', { orderId: ParamValue<true> }, { orderId: ParamValue<false> }>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/categories/': RouteRecordInfo<'/admin/categories/', '/admin/categories', Record<never, never>, Record<never, never>>,
    '/admin/categories/[categoryId]/edit': RouteRecordInfo<'/admin/categories/[categoryId]/edit', '/admin/categories/:categoryId/edit', { categoryId: ParamValue<true> }, { categoryId: ParamValue<false> }>,
    '/admin/categories/create': RouteRecordInfo<'/admin/categories/create', '/admin/categories/create', Record<never, never>, Record<never, never>>,
    '/admin/login/': RouteRecordInfo<'/admin/login/', '/admin/login', Record<never, never>, Record<never, never>>,
    '/admin/menu/': RouteRecordInfo<'/admin/menu/', '/admin/menu', Record<never, never>, Record<never, never>>,
    '/admin/orders': RouteRecordInfo<'/admin/orders', '/admin/orders', Record<never, never>, Record<never, never>>,
    '/admin/orders/active/': RouteRecordInfo<'/admin/orders/active/', '/admin/orders/active', Record<never, never>, Record<never, never>>,
    '/admin/orders/archived/': RouteRecordInfo<'/admin/orders/archived/', '/admin/orders/archived', Record<never, never>, Record<never, never>>,
    '/session/expired/': RouteRecordInfo<'/session/expired/', '/session/expired', Record<never, never>, Record<never, never>>,
    '/session/init/[table]/[time]/telegram': RouteRecordInfo<'/session/init/[table]/[time]/telegram', '/session/init/:table/:time/telegram', { table: ParamValue<true>, time: ParamValue<true> }, { table: ParamValue<false>, time: ParamValue<false> }>,
    '/session/init/[table]/web': RouteRecordInfo<'/session/init/[table]/web', '/session/init/:table/web', { table: ParamValue<true> }, { table: ParamValue<false> }>,
    '/session/table-not-found/': RouteRecordInfo<'/session/table-not-found/', '/session/table-not-found', Record<never, never>, Record<never, never>>,
    '/tg-mini-app/[orderId]/': RouteRecordInfo<'/tg-mini-app/[orderId]/', '/tg-mini-app/:orderId', { orderId: ParamValue<true> }, { orderId: ParamValue<false> }>,
  }
}
